config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/Open-EO/openeo-processes-dask:
      branch: main
      repo: https://github.com/Open-EO/openeo-processes-dask
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Open-EO/openeo-processes-dask git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-corn-starfish.sh
        container: qc.acc_messy-vermilion-flamingo
  QC.Doc:
    repos:
      github.com/Open-EO/openeo-processes-dask find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-heliotrope-wildebeest.sh
        container: qc.doc_baggy-cerulean-gerbil
      github.com/Open-EO/openeo-processes-dask git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-apricot-starfish.sh
        container: qc.doc_nippy-khaki-devil
      github.com/Open-EO/openeo-processes-dask markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-seashell-rottweiler.sh
        container: qc.doc_sleepy-plum-lionfish
  QC.Lic:
    repos:
      github.com/Open-EO/openeo-processes-dask licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-eggplant-robin.sh
        container: qc.lic_snappy-wisteria-tiger
  QC.Sec:
    repos:
      github.com/Open-EO/openeo-processes-dask bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-platinum-booby.sh
        container: qc.sec_scanty-alizarin-salamander
  QC.Sty:
    repos:
      github.com/Open-EO/openeo-processes-dask flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-rose-hippopotamus.sh
        container: qc.sty_sunny-yellow-toucan
      github.com/Open-EO/openeo-processes-dask jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-peach-frog.sh
        container: qc.sty_snippy-zucchini-shrimp
  QC.Uni:
    repos:
      github.com/Open-EO/openeo-processes-dask pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-russet-llama.sh
        container: qc.uni_gamy-russet-tapir
  QC.Ver:
    repos:
      github.com/Open-EO/openeo-processes-dask get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-amaranth-gar.sh
        container: qc.ver_cozy-razzmatazz-malamute
timeout: 5400
